@startuml

node 客户端 {

    node 管理中心PC {
        [就餐卡申请缴费界面]
    }

    node 监控中心PC {
        [监控界面]
    }

    node 收款机 {
        [收付款界面]
    }
}

node 服务端 {
    [注册缴费服务]
    [收付款服务]
    [监控服务]
}

客户端 ----> 服务端 : TCP/IP

database 数据存储
服务端 ----> 数据存储

@enduml