@startuml
actor 学生
actor 服务员
actor 管理员
participant 支付系统
participant 管理中心
participant 监控系统

== 注册缴费 ==
学生 -> 管理中心 : 注册
管理中心 -> 存储系统 : 新建就餐卡
管理中心 <- 存储系统 : OK
学生 <- 管理中心 : OK
学生 -> 管理中心 : 缴费
管理中心 -> 存储系统 : 增加就餐卡余额
管理中心 <- 存储系统 : OK
学生 <- 管理中心 : OK

== 支付 ==
学生 -> 支付系统 : 插卡
服务员 <- 支付系统 : 显示金额
服务员 -> 支付系统 : 收款
支付系统 -> 管理中心 : 扣款
管理中心 -> 存储系统 : 减少就餐卡余额
管理中心 <- 存储系统 : OK
支付系统 <- 管理中心 : OK
学生 <- 支付系统 : 显示消费额和余额

== 监控 ==
管理员 -> 监控系统 : 查看消费记录
监控系统 -> 存储系统 : 读取消费记录
监控系统 <- 存储系统 : 消费记录
监控系统 -> 监控系统 : 打印
管理员 <- 监控系统 : OK


@enduml